services:
    vite:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            target: dev
        ports:
            - '5173:5173'
        volumes:
            - ./frontend:/app
            - /app/node_modules
            - ./.env:/config/.env:ro
        restart: unless-stopped
