services:

    caddy:
        image: caddy:2.11.2
        ports:
          - '80:80'
          - '443:443'
        volumes:
            - ./caddy/Caddyfile:/etc/caddy/Caddy
            - caddy_data:/data
            - caddy_config:/config
        restart: unless-stopped

    api-express:
        build:
            context: ./backend
            target: dev
        ports:
            - '127.0.0.1:5555:5555'
        expose:
            - '3000'
        volumes:
            - ./backend/:/app/
        env_file:
            - .env
        networks:
            - hypertube-network
        depends_on:
            postgres_db:
                condition: service_healthy
        restart: unless-stopped
        
    postgres_db:
        image: postgres:17
        hostname: postgres_db
        container_name: postgres_db
        restart: always
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        networks:
            - hypertube-network
        healthcheck: 
                test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"] 
                interval: 5s
                timeout: 2s
                retries: 20
        volumes: 
            - postgres_data:/var/lib/postgresql/data
        command: postgres -c listen_addresses='*'
    
networks: 
    hypertube-network: 
volumes: 
    postgres_data: 
    caddy_data: 
    caddy_config: 
