services:    
    api-express:
        container_name: hypertube-express
        build:
            context: backend
        ports: 
            - "3000:3000"
        volumes:
             - ./backend/src:/app/src/